version: "3.8"

services:
  app:
    build: .
    container_name: ProFix-server
    restart: always
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
